Add flag to get KSKs from trust anchor instead of DNS
iana-org/get-trust-anchor pull request #21
Opened 2024-11-06 22:43 UTC by ethanent

This can be used to retrieve and validate KSKs that are not yet published in the root zone but that are published in `root-anchors.xml`, such as KSK-2024.

2024-11-13 20:20 UTC, ethanent commented
Hi @kjd, is it possible to get this reviewed? I would like to use this to validate KSK-2024.

2024-11-13 21:09 UTC, ethanent commented
Not sure exactly who the current maintainers are for this repo, but this change is ready for review. Thanks!

2024-11-24 16:33 UTC, jschlyter requested changes

2024-11-24 16:33 UTC, jschlyter commented on get_trust_anchor.py
> +    cmd_parse.add_argument("--ksks_from_trust_anchor", dest="ksks_from_trust_anchor", action='store_true',\
I suggest `--ksks-from-trust-achor` or  perhaps ´ksks-from-ta`

2024-11-24 16:33 UTC, jschlyter commented on get_trust_anchor.py
> +            except:
Match specific exception, not catch all.

2024-11-24 16:33 UTC, jschlyter commented on get_trust_anchor.py
> +        if not "PublicKey" in anchor or not "Flags" in anchor:
Use `X not in Y` instead of `not X in Y`

2024-12-01 09:50 UTC, jschlyter approved these changes
This change is ok, but the software as is does not work as indented - only the first TA is written. I'll take a look at that.

2024-12-01 17:10 UTC, ethanent commented
Thanks for the fix. Also noticed that during testing. Notably multiple trust anchors were produced, but were in separate files with all but one turned into .backup_{} files.

2024-12-02 19:56 UTC, merged